// Generated by copilot on behalf of Andrii

#include "InternalTemperatureSensor.hpp"
#include <ezTime.h>
#include "config.h"

// Constructor
// @param Id Sensor ID
InternalTempSensor::InternalTempSensor(int Id) {
    this->Id = Id;
    this->Type = TEMPERATURE;
    this->Name = "InternalTempSensor";
}

// Initializes the sensor (no-op for internal sensor)
void InternalTempSensor::Init() {
    // No initialization required for internal temperature sensor
}

// Reads the internal temperature
// @return Pointer to SensorData struct with reading
SensorData* InternalTempSensor::Read() {
    srand(UTC.second());

    SensorData *data = new SensorData();
    data->Id = this->Id;
    data->TimeStamp = UTC.dateTime(DATETIME_FORMAT_DEFAULT);
    data->Value = temperatureRead();
    return data;
}