// Generated by copilot on behalf of Andrii
#include "ISensor.hpp"

/// @brief Sensor that reads the internal temperature of the ESP32
/// Implements the ISensor interface
class InternalTempSensor : public ISensor {
    public:
        // Constructor
        // @param Id Sensor ID
        InternalTempSensor(int Id);

        // Initializes the sensor (no-op for internal sensor)
        void Init() override;

        // Reads the internal temperature
        // @return Pointer to SensorData struct with reading
        SensorData* Read() override;
};