#pragma once
// Generated by copilot on behalf of Andrii

#include <Arduino.h>
#include "Models/SensorDataStructs.hpp"

/// @brief Interface that defines a sensor
/// it defines the basic methods and properties that a sensor must have
class ISensor {
    public:
        int Id;
        String Name;
        SensorType Type;

        // Initializes the sensor
        virtual void Init() = 0;

        // Reads the sensor value
        // @return Pointer to SensorData struct with reading
        virtual SensorData* Read() = 0;
};