// Generated by copilot on behalf of Andrii
#include "ISensor.hpp"

/// @brief Sensor that reads soil moisture using a 
/// capacitive moisture sensor v2
/// Implements the ISensor interface
class MoistureSensor : public ISensor {
    public:
        int Pin;

        // Constructor
        // @param Id Sensor ID
        // @param Pin Analog pin for sensor
        MoistureSensor(int Id, int Pin);

        // Initializes the sensor hardware
        void Init() override;

        // Reads the sensor value
        // @return Pointer to SensorData struct with reading
        SensorData* Read() override;
};