// Generated by copilot on behalf of Andrii

#include "MoistureSensor.hpp"
#include <ezTime.h>
#include "config.h"

// Constructor
// @param Id Sensor ID
// @param Pin Analog pin for sensor
MoistureSensor::MoistureSensor(int Id, int Pin) {
    this->Id = Id;
    this->Pin = Pin;
    this->Type = SOIL_CAP;
    this->Name = "SoilMoisture";
}

// Initializes the sensor hardware
void MoistureSensor::Init() {
    pinMode(Pin, INPUT);
}

// Reads the sensor value
// @return Pointer to SensorData struct with reading
SensorData* MoistureSensor::Read() {
    srand(UTC.second());

    SensorData *data = new SensorData();
    data->Id = this->Id;
    data->TimeStamp = UTC.dateTime(DATETIME_FORMAT_DEFAULT);
    data->Value = analogRead(this->Pin);
    return data;
}