// Generated by copilot on behalf of Andrii

#include "SmartSensor.hpp"
#include <ezTime.h>
#include "config.h"
#include <Wire.h>
#include <Arduino.h>

#define SMARTSENSOR_CMD_REQUESTDATA 0x10
#define SMARTSENSOR_CMD_SETACTION 0x20

#define SMARTSENSOR_CMD_ARG_READ_MOISTURE 0x01
#define SMARTSENSOR_CMD_ARG_READ_HUMIDITY 0x02
#define SMARTSENSOR_CMD_ARG_READ_SOILTEMPERATURE 0x03   
#define SMARTSENSOR_CMD_ARG_READ_AIRTEMPERATURE 0x04   

#define PACKET_LENGTH_REQUEST 3
#define PACKET_LENGTH_RESPONSE 5

// Constructor
// @param Id Sensor ID
SmartSensor::SmartSensor(int Id, uint8_t i2cAddress, uint8_t PinSDA, uint8_t PinSCL) {
    this->Id = Id;
    this->Type = SMART_SOIL_MOISTURE;
    this->Name = "SmartSensor";
    this->PinSDA = PinSDA;
    this->PinSCL = PinSCL;
    this->I2CAddress = i2cAddress;
}

// Initializes the Smart sensor
void SmartSensor::Init() {
    
}

// Reads a simulated value
// @return Pointer to SensorData struct with reading
SensorData* SmartSensor::Read() {
    //Send command what type of data we want to read
    SetReadAction(SMARTSENSOR_CMD_ARG_READ_MOISTURE);
    //Send I2C request and read data
    uint8_t* receiveBuffer = ReadAction();
    
    int value = 0;

    if (CheckSumValid(receiveBuffer, PACKET_LENGTH_RESPONSE)) {
        value = (receiveBuffer[3] << 8) | receiveBuffer[4];
    } else {
        Serial.println("I2C Transition failed. Checksum invalid, return null");
    }
 
    SensorData *data = new SensorData();
    data->Id = this->Id;
    data->TimeStamp = UTC.dateTime(DATETIME_FORMAT_DEFAULT);
    data->Value = value;
    return data;
}

/// Checks if data packet checksum is valid
/// according to transmition protocol the checksum is always 3rd byte in packet
/// @param dataBuffer Pointer to data buffer
/// @param length Length of the data buffer
bool SmartSensor::CheckSumValid(uint8_t* dataBuffer, uint8_t length) {
    
    uint8_t checksum = dataBuffer[0];
    for(uint8_t i = 1; i < length; i++) {
        if (i == 2) continue; // Skip checksum byte
        checksum ^= dataBuffer[i];
    }
    
    // Compare calculated checksum with received checksum
    return checksum == dataBuffer[2];
}

void SmartSensor::SetReadAction(uint8_t dataType){
    //Send command what type of data we want to read
    uint8_t commandPacket[PACKET_LENGTH_REQUEST];
    commandPacket[0] = SMARTSENSOR_CMD_SETACTION;
    commandPacket[1] = dataType;
    commandPacket[2] = commandPacket[0] ^ commandPacket[1]; // Checksum
    //Send I2C request and read data
    
    Wire.begin(this->PinSDA, this->PinSCL);
    Wire.beginTransmission(this->I2CAddress);
    Wire.write(commandPacket, PACKET_LENGTH_REQUEST);
    Wire.endTransmission();
    Wire.end();
}

uint8_t* SmartSensor::ReadAction() {

    Wire.begin(this->PinSDA, this->PinSCL);
        
    uint8_t bytesReceived = Wire.requestFrom(this->I2CAddress, (uint8_t)PACKET_LENGTH_RESPONSE);
    uint8_t* receiveBuffer = new uint8_t[bytesReceived];

    if ((bool)bytesReceived){
        Wire.readBytes(receiveBuffer, bytesReceived);    
    }

    return receiveBuffer;
}
