// Generated by copilot on behalf of Andrii

#include "TemperatureSensor.hpp"
#include <ezTime.h>
#include "Config/config.h"

// Constructor
// @param Id Sensor ID
// @param Pin GPIO pin for 1-Wire bus
TemperatureSensor::TemperatureSensor(int Id, int Pin)
    : oneWire(Pin), sensors(&oneWire) {
    this->Id = Id;
    this->Pin = Pin;
    this->Type = TEMPERATURE;
    this->Name = "SoilTemperature";
}

// Initializes the sensor hardware
void TemperatureSensor::Init() {
    this->sensors.begin();
}

// Reads the sensor value
// @return Pointer to SensorData struct with reading
SensorData* TemperatureSensor::Read() {
    srand(UTC.second());

    SensorData *data = new SensorData();
    data->Id = this->Id;
    data->TimeStamp = UTC.dateTime(DATETIME_FORMAT_DEFAULT);
    this->sensors.requestTemperatures();
    data->Value = this->sensors.getTempCByIndex(0);
    return data;
}