#pragma once
// Generated by copilot on behalf of Andrii

#include "OneWire.h"
#include "DallasTemperature.h"
#include "ISensor.hpp"

/// @brief Sensor that reads soil temperature using a 
/// Dallas OneWire temperature sensor
/// Implements the ISensor interface
class TemperatureSensor : public ISensor {
    private:
        OneWire oneWire;
        DallasTemperature sensors;

    public:
        int Pin;
        int Data;

        // Constructor
        // @param Id Sensor ID
        // @param Pin GPIO pin for 1-Wire bus
        TemperatureSensor(int Id, int Pin);

        // Initializes the sensor hardware
        void Init() override;

        // Reads the sensor value
        // @return Pointer to SensorData struct with reading
        SensorData* Read() override;
};