// Generated by copilot on behalf of Andrii

#include "VirtualSensor.hpp"
#include <ezTime.h>
#include "Config/config.h"

// Constructor
// @param Id Sensor ID
VirtualSensor::VirtualSensor(int Id) {
    this->Id = Id;
    this->Type = VIRTUAL;
    this->Name = "VirtualSensor";
}

// Initializes the virtual sensor
void VirtualSensor::Init() {
    srand(millis());
}

// Reads a simulated value
// @return Pointer to SensorData struct with reading
SensorData* VirtualSensor::Read() {
    SensorData *data = new SensorData();
    data->Id = this->Id;
    data->TimeStamp = UTC.dateTime(DATETIME_FORMAT_DEFAULT);
    data->Value = rand() % 3600 + 1650;
    return data;
}