// Generated by copilot on behalf of Andrii

#pragma once
#include <Arduino.h>
#include <FS.h>
#include <SPIFFS.h>
#include <vector>

// Wrapper class for SPIFFS file operations
class FileSystem {
public:
    // Reads the contents of a file at the given file path.
    // @param filePath Path to the file to read.
    // @return String containing the file contents, or empty string if not found.
    static String Read(const String& filePath);

    // Creates a new file at the given file path (overwrites if exists).
    // @param filePath Path to the file to create.
    // @return true if file was created successfully, false otherwise.
    static bool Create(const String& filePath);

    // Appends a line to a file at the given file path.
    // @param filePath Path to the file to append to.
    // @param data String to append as a new line.
    // @return true if append was successful, false otherwise.
    static bool Append(const String& filePath, const String& data);

    // Lists all files in the given directory.
    // @param dirPath Path to the directory to list.
    // @return Vector of file names as strings.
    static std::vector<String> List(const String& dirPath);

    // Checks if a file exists at the given file path.
    // @param filePath Path to the file to check.
    // @return true if file exists, false otherwise.
    static bool Exists(const String& filePath);
};
