// Generated by copilot on behalf of Andrii
#include "ISensor.hpp"

// SmartSensor Packet description:

// Command Data packet structure:
// ||    Byte 0  |    Byte 1  |    Byte 2  ||
// ||  HEADER H  |  HEADER L  |  CHECKSUM  ||
// ||--CCCCCCCC--|--OOOOOOOO--|--XXXXXXXX--||
//  CC : Commmand 8 bits; 0x10 - Request Data, 0x20 : Set Action
//  OO : Commmand operand; 0x10 - Sensor 1; 0x20 - Sensor 2
//  XX : Checksum. XOR of bytes 2,1,0

// Response Data packet structure:
// ||    Byte 0  |    Byte 1  |    Byte 2  |   Byte 3   |   Byte 4   ||
// ||  HEADER H  |  HEADER L  |  CHECKSUM  |   Value H  |   Value L  ||
// ||--IIIIIIII--|--SSS000BB--|--XXXXXXXX--|--HHHHHHHH--|--LLLLLLLL--||
//  XX : Checksum. XOR of bytes 3,1,0
//  BB - ADC Bits. 00: None, 01: 10bits; 10:12bits; 11:16bits
//  SS - SensorType Type. 
//       000: none, 
//       001: MOISTURE, 
//       010: HUMIDITY, 
//       011: SOIL TEMPERATURE, 
//       100: AIR TEMPERATURE
//       101: RESERVED,
//       110: RESERVED,
//       111: RESERVED,
//
//  II - Device Signature.
//  00 - RESERVED

/// @brief Sensor that generates virtual sensor data used as stub for testing
/// Implements the ISensor interface
class SmartSensor : public ISensor {
    private:
        uint8_t PinSDA;
        uint8_t PinSCL;
        uint8_t I2CAddress;

        bool CheckSumValid(uint8_t* dataBuffer, uint8_t length);
        void SetReadAction(uint8_t dataType);
        uint8_t* ReadAction();

    public:
        // Constructor
        // @param Id Sensor ID
        // @param PinSDA GPIO pin for SDA
        // @param PinSCL GPIO pin for SCL
        SmartSensor(int Id, uint8_t i2cAddress, uint8_t PinSDA, uint8_t PinSCL);

        // Initializes the Smart sensor
        void Init() override;

        // Reads a simulated value
        // @return Pointer to SensorData struct with reading
        SensorData* Read() override;
};