// Generated by copilot on behalf of Andrii
#include "ISensor.hpp"

/// @brief Sensor that generates virtual sensor data used as stub for testing
/// Implements the ISensor interface
class VirtualSensor : public ISensor {
    public:
        // Constructor
        // @param Id Sensor ID
        VirtualSensor(int Id);

        // Initializes the virtual sensor
        void Init() override;

        // Reads a simulated value
        // @return Pointer to SensorData struct with reading
        SensorData* Read() override;
};