// Generated by copilot on behalf of Andrii
#pragma once

#include <ESPAsyncWebServer.h>

// Handles the pour action API endpoint
// @param request Pointer to the AsyncWebServerRequest object representing the HTTP request
// @return void. Sends HTTP response directly via the request object
void actionPour(AsyncWebServerRequest * request, uint8_t *data, size_t len, size_t index, size_t total);