// Generated by copilot on behalf of Andrii
#include "config/config.h"


#include "Api/ActionsApi.hpp"
#include "Api/ApiTools.hpp"
#include "Models/Actuators/IActuator.hpp"
#include "Models/ActionRequest.hpp"
#include <ArduinoJson.h>

extern IActuator *actuatorArray[];
extern int actuatorArraySize;

// Handles the pour action API endpoint
// @param request Pointer to the AsyncWebServerRequest object representing the HTTP request
// @param data - buffer for the request body
// @param len - length of the data buffer
// @param index - not clearly understendable from documentation. Probably used when data is sent in chunks
// @param total - not clearly understendable from documentation. Probably used when data is sent in chunks
// @return void. Sends HTTP response directly via the request object
void actionPour(AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total) {
    Serial.println("Pour action triggered");

    String body = String((const char*)data, len);

    JsonDocument doc;
    DeserializationError error = deserializeJson(doc, body);

    if (error) {
        Serial.print(F("deserializeJson() failed: "));
        Serial.println(error.f_str());
        request->send(400, "text/plain", "Invalid JSON");
        return;
    }

    Serial.println(body);
 
    request->send(200);
    
    ActionRequest requestData;
    requestData.deviceId = doc["deviceId"].as<String>();
    requestData.actionName = doc["actionName"].as<String>();
    requestData.value = doc["value"].as<int>();
    
    if (requestData.value <= 0 || requestData.value > LIMIT_POUR_DURATION) {
        request->send(400, "text/plain", "Invalid duration value");
        return;
    }

    actuatorArray[0]->Act(requestData.value);
    request->send(200, "text/plain", "Pour action executed");
}

