# Generated by copilot on behalf of Andrii
# PowerShell script to download all readings from PotWarden REST API
# Usage:
#   .\download_readings.ps1 -BaseUrl 'http://pot-warden' -OutputDir 'C:\Temp\readings'

param(
  [string]$BaseUrl = 'http://pot-warden',
  [string]$OutputDir = "$PSScriptRoot\..\temp\readings"
)

# Create output folder if missing
if (-not (Test-Path -Path $OutputDir)) {
  New-Item -Path $OutputDir -ItemType Directory | Out-Null
}

$listUrl = "$BaseUrl/sensor/data/list"

try {
  Write-Host "Requesting file list from $listUrl ..."
  $resp = Invoke-RestMethod -Uri $listUrl -Method Get -ErrorAction Stop
  Write-Host "Response received:"
  Write-Host ($resp | ConvertTo-Json -Depth 5)
} catch {
  Write-Error "Failed to get file list: $_"
  exit 1
}

if (-not $resp.files -or $resp.files.Count -eq 0) {
  Write-Host "No files reported by server."
  exit 0
}

foreach ($entry in $resp.files) {
  # entry expected like "/readings/<item>.csv"
  $fileName = [System.IO.Path]::GetFileName($entry)
  if ([string]::IsNullOrEmpty($fileName)) { continue }

  $encoded = [System.Uri]::EscapeDataString($fileName)
  $fileUrl = "$BaseUrl/sensor/data/file?file=$encoded"
  $outPath = Join-Path $OutputDir $fileName

  # Write-Host "Downloading $fileName ..."
  
  try {
    Write-Host "$fileUrl"
    Invoke-WebRequest -Uri $fileUrl -OutFile $outPath -ErrorAction Stop
    Write-Host "Saved -> $outPath"
  } catch {
    Write-Warning "Failed to download $fileName : $($_.Exception.Message)"
  }
}