#pragma once
// Generated by copilot on behalf of Andrii

#include "Models/Sensors/ISensor.hpp"
#include "Api/ApiTools.hpp"

extern ISensor *sensorArray[];
extern int sensorArraySize;
extern SensorData **data;

// Gets the current UTC time and sends it as a response
// @param request Pointer to the AsyncWebServerRequest
// @return Sends a plain text response with the current time
void getTime(AsyncWebServerRequest *request);

// Gets sensor data by id and sends as JSON
// @param request Pointer to the AsyncWebServerRequest
// @return Sends a JSON response with sensor data
void getSensorData(AsyncWebServerRequest *request);

// Lists all sensors as JSON
// @param request Pointer to the AsyncWebServerRequest
// @return Sends a JSON response with all sensors
void listSensors(AsyncWebServerRequest *request);

// Sends a file from the readings directory
// @param request Pointer to the AsyncWebServerRequest
// @return Sends the file as a response
void getDataFile(AsyncWebServerRequest *request);

// Lists all files in the readings directory as JSON
// @param request Pointer to the AsyncWebServerRequest
// @return Sends a JSON response with file names
void listDataFiles(AsyncWebServerRequest *request);
