#pragma once

#define INTERVAL_SECOND   1000
#define INTERVAL_MINUTE   60000
#define INTERVAL_HOUR     360000

#define INTERVAL_STATUS_LED 2 * INTERVAL_SECOND
#define INTERVAL_READ_SENSORS 25 * INTERVAL_SECOND